---
title: "Methods"
author: "Colin Mahony"
date: "27/11/2020"
output: html_document
---

## About this app

This is a draft app to explore Biogeoclimatic projections at the landscape scale. The purpose of the app at this early stage in its development is to solicit feedback on what types of information will be useful to resource managers. 

### Contributors
App created by:<br>
Colin Mahony<br>
Research Climatologist<br>
BC Ministry of Forests, Lands, Natural Resource Operations and Rural Development<br>
colin.mahony@gov.bc.ca

### Methods

This app follows the methods described in [MacKenzie and Mahony (2021)](https://www.researchgate.net/profile/Colin_Mahony/publication/345634719_An_ecological_approach_to_climate_change-informed_tree_species_selection_for_reforestation/links/5fa98d28a6fdcc062420460a/An-ecological-approach-to-climate-change-informed-tree-species-selection-for-reforestation.pdf). 

**Summary values**--All values presented in the summary figures are averages of the full set of raster values shown on the maps. 

**Climate Data**--All climate data are derived from [ClimateBC](http://climatebc.ca/), a public climate downscaling software developed by Tongli Wang at the UBC Centre for Forest Conservation Genetics. 

**Climate Variables**--Although there are many types of climate variables in this app, values for many of these variables are estimated from monthly values of three basic climate elements: mean daily maximum temperature (T<sub>max</sub>), mean daily minimum temperature (T<sub>min</sub>), and precipitation (PPT). The method for estimating derived variables is given in [Wang et al. (2016)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0156720). Since other climate elements (e.g., degree-days, precipitation as snow, frost-free days, cumulative moisture deficit) are not calculated directly from daily data, some caution is warranted. 

**Climate Models**--This app features 9 of the 13 climate models that are available in ClimateBC; Three of the models are excluded because their equilibrium climate sensitivity (ECS) exceeds a range supported by multiple lines of evidence (<a href="https://advances.sciencemag.org/content/advances/6/12/eaaz9549.full.pdf" target="_blank">Tokarska et al. 2020</a>; <a href="https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019GL086757" target="_blank">Liang et al. 2020</a>; <a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2019RG000678?fbclid=IwAR0RaslfRZtPcbi_RjZS3wnHWralh0GuoMyJ9NSbgAOOezP0VyTHgrfdlrs" target="_blank">Sherwood et al. 2020</a>). More information on the models and their selection criteria can be found at the <a href='https://bcgov-env.shinyapps.io/cmip6-BC/' target='_blank'>cmip-BC app</a>. 

**Emissions scenario**--This app features a single emissions scenario, <a href="https://www.carbonbrief.org/explainer-how-shared-socioeconomic-pathways-explore-future-climate-change" target="_blank">SSP2-4.5</a>, which prescribes a peak in human greenhouse gas emissions by 2040, and a decline towards half of year-1970 emissions by the year 2100. This scenario is roughly in line with current national commitments under the Paris accord, and consistent with a global temperature rise of approximately 2.6<sup>o</sup>C by the year 2100. 


